DROP TABLE IF EXISTS job;

CREATE TABLE job (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  status STRING NOT NULL DEFAULT "INACTIVE",
  transform_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed TIMESTAMP,
  filerefs_json TEXT NOT NULL,
);
